// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    partial class AnimalShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.HasKey("CatId");

                    b.ToTable("Cat");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Age = 1,
                            Gender = "Female",
                            Name = "Catrina McMeow"
                        },
                        new
                        {
                            CatId = 2,
                            Age = 2,
                            Gender = "Male",
                            Name = "Henry Hiss"
                        },
                        new
                        {
                            CatId = 3,
                            Age = 2,
                            Gender = "Female",
                            Name = "Pamela Pushitoff"
                        },
                        new
                        {
                            CatId = 4,
                            Age = 3,
                            Gender = "Male",
                            Name = "Benjamin Bartholomeow"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.HasKey("DogId");

                    b.ToTable("Dog");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Age = 1,
                            Gender = "Male",
                            Name = "Mathias McDog"
                        },
                        new
                        {
                            DogId = 2,
                            Age = 2,
                            Gender = "Female",
                            Name = "Sally Sandwichstealer"
                        },
                        new
                        {
                            DogId = 3,
                            Age = 2,
                            Gender = "Male",
                            Name = "Peter Poopeater"
                        },
                        new
                        {
                            DogId = 4,
                            Age = 3,
                            Gender = "Female",
                            Name = "Samantha Sniffsalot"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
